name: Release
on:
  release:
      types: [created]
jobs:
  build:
    runs-on: windows-2022
    
    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-java@v3
       with:
         java-version: 20
         distribution: "oracle"
     - run: mvn verify
     - uses: actions/upload-artifact@v3
       with:
           name: dforg
           path: 'target/release'
     - uses: AButler/upload-release-assets@v2.0
       with:
         files: 'target/release/*'
         repo-token: ${{ secrets.TOKEN }}